### ISSUE TITLE
add authors to storylines

### ISSUE THREAD

**Issue by uf0** [calibro/campscapes#20]

**Comment by uf0** [comment]
`Creator` inside item
`external_url `inside item_type == site

**Comment by bianchimro** [comment]
Parser coverts these fields to arrays (in all cases):
- data.creator 
- data.externalUrl

**Comment by uf0** [comment]
add splitting inside single field (comma separated)

**Comment by uf0** [comment]
add to story level `creator` field with all the creators coming from the attachments (DUPLICATES!)

**Comment by bianchimro** [comment]
should be ok

**Comment by uf0** [comment]
found duplicates (story id: `47`)

![Screen Shot 2019-11-15 at 16 38 12](https://user-images.githubusercontent.com/1922342/68955721-f2fff080-07c6-11ea-8055-78cb91776013.png)
